
[pytest]
markers =
    smoke:      冒烟测试，核心流程
    P0:         阻塞级，每次提交必跑
    P1:         主流程，每次发布前跑
    P2:         边界异常，全量回归跑
    P3:         非核心业务，周期性回归
    P4:         系统管理级，发版前专项跑

addopts =
    -v
    --tb=short
    --reruns=2
    --reruns-delay=1
    --alluredir=reports/allure-results
    -p no:warnings

log_cli = true
log_cli_level = INFO
testpaths = api_test/testcase