[pytest]
makers = smoke:冒烟测试
addopts = -s --alluredir report --clean-alluredir
testpaths = ./script
# python_files = test*.py
python_files = test_01_login.py
python_classes = Test*
python_functions = test*